version: '3'
services:
  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    volumes:
      - ./sigsci_rules_export.db:/metabase-data/sigsci_rules_export.db
